using SOMIOD.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Linq;
using System.Net;
using System.Web.Http;
using System.Web.Http.Description;

namespace SOMIOD.Controllers
{
    [RoutePrefix("api/somiod")]
    public class ApplicationController : ApiController
    {
        // Connection String (Garante que no Web.config tens <add name="ConnStr" ... />)
        private string connectionString = ConfigurationManager.ConnectionStrings["ConnStr"].ConnectionString;

        // =============================================================
        // 1. OPERAÇÕES NA RAIZ DO SISTEMA (api/somiod/)
        // =============================================================

        /// <summary>
        /// Cria uma nova aplicação.
        /// </summary>
        /// <remarks>
        /// Cria um registo de uma nova aplicação no middleware.
        /// Se o <b>resource-name</b> não for fornecido, o sistema gera um nome único automaticamente.
        /// 
        /// **Exemplo de Pedido:**
        /// 
        ///     POST /api/somiod
        ///     {
        ///        "res-type": "application",
        ///        "resource-name": "smart-parking"
        ///     }
        /// </remarks>
        /// <param name="app">O modelo da aplicação a criar.</param>
        /// <returns>Os dados da aplicação criada, incluindo o nome gerado e data.</returns>
        /// <response code="201">Sucesso: Aplicação criada (retorna o objeto completo).</response>
        /// <response code="400">Erro: O 'res-type' é inválido ou nulo.</response>
        /// <response code="409">Conflito: Já existe uma aplicação com esse nome (se fornecido manualmente).</response>
        /// <response code="500">Erro interno do servidor.</response>
        [ResponseType(typeof(ApplicationModel))]
        [HttpPost]
        [Route("")]
        public IHttpActionResult PostApplication([FromBody] ApplicationModel app)
        {
            if (app == null) app = new ApplicationModel();

            if (app.ResType.ToLower() != "application")
                return BadRequest("O tipo de recurso deve ser 'application'.");

            bool isAutoGenerated = string.IsNullOrEmpty(app.ResourceName);
            if (isAutoGenerated)
                app.ResourceName = "App_" + Guid.NewGuid().ToString().Substring(0, 8);

            app.CreationDateTime = DateTime.Now;

            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                conn.Open();
                while (true) // Retry logic para nomes auto-gerados
                {
                    string sql = "INSERT INTO Applications (Name, CreationDate) VALUES (@name, @date)";
                    SqlCommand cmd = new SqlCommand(sql, conn);
                    cmd.Parameters.AddWithValue("@name", app.ResourceName);
                    cmd.Parameters.AddWithValue("@date", app.CreationDateTime);

                    try
                    {
                        cmd.ExecuteNonQuery();
                        break;
                    }
                    catch (SqlException ex)
                    {
                        if (ex.Number == 2627) // Violação de Unique Constraint
                        {
                            if (isAutoGenerated)
                            {
                                app.ResourceName = "App_" + Guid.NewGuid().ToString().Substring(0, 8);
                                continue;
                            }
                            else
                            {
                                return Content(HttpStatusCode.Conflict, "Resource name already exists.");
                            }
                        }
                        return InternalServerError(ex);
                    }
                }
            }
            return Content(HttpStatusCode.Created, app);
        }

        /// <summary>
        /// Ponto de entrada do sistema e Descoberta Global (Discovery).
        /// </summary>
        /// <remarks>
        /// Este endpoint permite listar todas as aplicações ou realizar a descoberta de recursos globais.
        /// O comportamento é controlado pelo cabeçalho HTTP **somiod-discovery**.
        /// 
        /// **Valores suportados no Header:**
        /// * `application` (ou omitido): Retorna a lista de todas as Aplicações registadas.
        /// * `subscription`: Retorna a lista de TODAS as subscrições existentes em todo o sistema (recursivamente).
        /// 
        /// **Exemplo de Resposta (JSON):**
        /// 
        ///     [
        ///         "/api/somiod/smart-parking",
        ///         "/api/somiod/lighting"
        ///     ]
        /// </remarks>
        /// <returns>Uma lista de strings com os URIs (caminhos) dos recursos encontrados.</returns>
        /// <response code="200">Sucesso: Retorna a lista de recursos (pode ser vazia).</response>
        [ResponseType(typeof(List<string>))]
        [HttpGet]
        [Route("")]
        public IHttpActionResult GetSystemRoot()
        {
            var headers = Request.Headers;
            string discoveryType = headers.Contains("somiod-discovery")
                ? headers.GetValues("somiod-discovery").First().ToLower()
                : "application";

            List<string> results = new List<string>();

            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                conn.Open();

                // Discovery: Listar todas as Apps
                if (discoveryType == "application")
                {
                    string sql = "SELECT Name FROM Applications";
                    SqlCommand cmd = new SqlCommand(sql, conn);
                    SqlDataReader reader = cmd.ExecuteReader();
                    while (reader.Read())
                    {
                        results.Add("/api/somiod/" + reader["Name"].ToString());
                    }
                }
                // Discovery: Listar TODAS as subscrições do sistema
                else if (discoveryType == "subscription")
                {
                    string sql = @"SELECT S.Name AS SubName, C.Name AS ContName, A.Name AS AppName 
                                   FROM Subscriptions S
                                   JOIN Containers C ON S.ParentContainerId = C.Id
                                   JOIN Applications A ON C.ParentAppId = A.Id";

                    SqlCommand cmd = new SqlCommand(sql, conn);
                    SqlDataReader reader = cmd.ExecuteReader();
                    while (reader.Read())
                    {
                        string path = $"/api/somiod/{reader["AppName"]}/{reader["ContName"]}/subs/{reader["SubName"]}";
                        results.Add(path);
                    }
                }
                // Outros tipos retornam lista vazia na raiz
                else
                {
                    return Ok(results);
                }
            }
            return Ok(results);
        }

        // =============================================================
        // 2. OPERAÇÕES EM UMA APLICAÇÃO (api/somiod/{name})
        // =============================================================

        /// <summary>
        /// Obtém os dados de uma aplicação ou descobre recursos filhos.
        /// </summary>
        /// <remarks>
        /// **Comportamento Padrão:**
        /// Sem cabeçalhos adicionais, retorna os metadados da aplicação (id, nome, data).
        /// 
        /// **Comportamento Discovery (Header `somiod-discovery`):**
        /// * `container`: Retorna uma lista de URIs dos contentores desta aplicação. 
        /// * `subscription`: Retorna uma lista de URIs das subscrições (dentro dos contentores) desta aplicação.
        /// </remarks>
        /// <param name="name">O nome único da aplicação.</param>
        /// <returns>Um objeto ApplicationModel (JSON) ou uma lista de Strings (JSON).</returns>
        /// <response code="200">Sucesso (retorna o recurso ou a lista).</response>
        /// <response code="404">Aplicação não encontrada.</response>
        [ResponseType(typeof(ApplicationModel))]
        [HttpGet]
        [Route("{name}")]
        public IHttpActionResult GetApplication(string name)
        {
            // 1. Verificar se a App existe
            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                conn.Open();
                string sqlCheck = "SELECT Count(*) FROM Applications WHERE Name = @name";
                SqlCommand cmdCheck = new SqlCommand(sqlCheck, conn);
                cmdCheck.Parameters.AddWithValue("@name", name);

                if ((int)cmdCheck.ExecuteScalar() == 0) return NotFound();
            }

            // 2. Lógica de Discovery (Headers)
            var headers = Request.Headers;
            if (headers.Contains("somiod-discovery"))
            {
                string discoveryType = headers.GetValues("somiod-discovery").First().ToLower();
                List<string> results = new List<string>();

                using (SqlConnection conn = new SqlConnection(connectionString))
                {
                    conn.Open();

                    if (discoveryType == "application")
                    {
                        return Ok(results); // Apps não têm apps filhas
                    }
                    else if (discoveryType == "container")
                    {
                        string sql = @"SELECT C.Name FROM Containers C 
                                       INNER JOIN Applications A ON C.ParentAppId = A.Id 
                                       WHERE A.Name = @appName";
                        SqlCommand cmd = new SqlCommand(sql, conn);
                        cmd.Parameters.AddWithValue("@appName", name);
                        SqlDataReader reader = cmd.ExecuteReader();
                        while (reader.Read())
                        {
                            results.Add("/api/somiod/" + name + "/" + reader["Name"].ToString());
                        }
                    }
                    else if (discoveryType == "subscription")
                    {
                        string sql = @"SELECT S.Name AS SubName, C.Name AS ContName
                                       FROM Subscriptions S
                                       JOIN Containers C ON S.ParentContainerId = C.Id
                                       JOIN Applications A ON C.ParentAppId = A.Id
                                       WHERE A.Name = @appName";

                        SqlCommand cmd = new SqlCommand(sql, conn);
                        cmd.Parameters.AddWithValue("@appName", name);
                        SqlDataReader reader = cmd.ExecuteReader();
                        while (reader.Read())
                        {
                            string path = $"/api/somiod/{name}/{reader["ContName"]}/subs/{reader["SubName"]}";
                            results.Add(path);
                        }
                    }
                }
                return Ok(results);
            }

            // 3. GET Normal (Retornar metadados)
            ApplicationModel app = null;
            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                conn.Open();
                string sql = "SELECT * FROM Applications WHERE Name = @name";
                SqlCommand cmd = new SqlCommand(sql, conn);
                cmd.Parameters.AddWithValue("@name", name);

                SqlDataReader reader = cmd.ExecuteReader();
                if (reader.Read())
                {
                    app = new ApplicationModel
                    {
                        Id = (int)reader["Id"],
                        ResourceName = (string)reader["Name"],
                        CreationDateTime = (DateTime)reader["CreationDate"],
                        ResType = "application"
                    };
                }
            }

            if (app == null) return NotFound();
            return Ok(app);
        }

        /// <summary>
        /// Atualiza uma aplicação existente.
        /// </summary>
        /// <remarks>
        /// Permite alterar o nome de uma aplicação existente.
        /// 
        /// **Nota:** O novo nome (`resource-name`) não pode estar a ser usado por outra aplicação.
        /// 
        /// **Exemplo de Pedido:**
        /// 
        ///     PUT /api/somiod/smart-parking
        ///     {
        ///        "res-type": "application",
        ///        "resource-name": "smart-parking-v2"
        ///     }
        /// </remarks>
        /// <param name="name">O nome atual da aplicação a atualizar.</param>
        /// <param name="app">O objeto contendo os novos dados (novo nome).</param>
        /// <returns>Os dados da aplicação atualizada.</returns>
        /// <response code="200">Sucesso: Aplicação atualizada.</response>
        /// <response code="400">Erro: Dados inválidos ou tipo de recurso incorreto.</response>
        /// <response code="404">Erro: A aplicação especificada não foi encontrada.</response>
        /// <response code="409">Conflito: O novo nome já existe noutra aplicação.</response>
        [ResponseType(typeof(ApplicationModel))]
        [HttpPut]
        [Route("{name}")]
        public IHttpActionResult PutApplication(string name, [FromBody] ApplicationModel app)
        {
            if (app == null) return BadRequest("Dados inválidos.");
            if (app.ResType.ToLower() != "application") return BadRequest("Tipo incorreto.");

            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                conn.Open();

                // Verificar existência
                string sqlCheck = "SELECT Count(*) FROM Applications WHERE Name = @name";
                SqlCommand cmdCheck = new SqlCommand(sqlCheck, conn);
                cmdCheck.Parameters.AddWithValue("@name", name);

                if ((int)cmdCheck.ExecuteScalar() == 0) return NotFound();

                // Atualizar
                string sqlUpdate = "UPDATE Applications SET Name = @newName WHERE Name = @oldName";
                SqlCommand cmdUpdate = new SqlCommand(sqlUpdate, conn);
                cmdUpdate.Parameters.AddWithValue("@newName", app.ResourceName);
                cmdUpdate.Parameters.AddWithValue("@oldName", name);

                try
                {
                    cmdUpdate.ExecuteNonQuery();
                }
                catch (SqlException ex)
                {
                    if (ex.Number == 2627) return Content(HttpStatusCode.Conflict, "New name is already in use.");
                    return InternalServerError(ex);
                }
            }
            return Ok(app);
        }

        /// <summary>
        /// Remove uma aplicação existente.
        /// </summary>
        /// <remarks>
        /// Apaga a aplicação da base de dados. 
        /// **Atenção:** Devido à configuração da Base de Dados (Cascade Delete), isto irá apagar também todos os contentores e subscrições associados.
        /// </remarks>
        /// <param name="name">O nome da aplicação a remover.</param>
        /// <returns>Sem conteúdo.</returns>
        /// <response code="200">Sucesso: A aplicação foi apagada.</response>
        /// <response code="404">Erro: A aplicação não foi encontrada.</response>
        [ResponseType(typeof(void))]
        [HttpDelete]
        [Route("{name}")]
        public IHttpActionResult DeleteApplication(string name)
        {
            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                string sql = "DELETE FROM Applications WHERE Name = @name";
                SqlCommand cmd = new SqlCommand(sql, conn);
                cmd.Parameters.AddWithValue("@name", name);
                conn.Open();

                if (cmd.ExecuteNonQuery() == 0) return NotFound();
            }
            return Ok();
        }

        // =============================================================
        // 3. CRIAÇÃO DE FILHOS (CONTAINERS)
        // Este método tem de estar aqui porque o URL é api/somiod/{appName}
        // =============================================================

        /// <summary>
        /// Cria um novo contentor dentro de uma aplicação.
        /// </summary>
        /// <remarks>
        /// Cria um registo de um novo contentor associado à aplicação especificada na rota.
        /// Se o <b>resource-name</b> não for fornecido, o sistema gera um nome único automaticamente.
        /// 
        /// **Exemplo de Pedido:**
        /// 
        ///     POST /api/somiod/smart-parking
        ///     {
        ///        "res-type": "container",
        ///        "resource-name": "piso-01"
        ///     }
        /// </remarks>
        /// <param name="name">O nome da aplicação pai onde o contentor será criado.</param>
        /// <param name="container">O modelo do contentor a criar.</param>
        /// <returns>Os dados do contentor criado.</returns>
        /// <response code="201">Sucesso: Contentor criado.</response>
        /// <response code="400">Erro: Tipo de recurso inválido (deve ser 'container') ou dados nulos.</response>
        /// <response code="404">Erro: A aplicação pai especificada não foi encontrada.</response>
        /// <response code="409">Conflito: Já existe um contentor com esse nome nesta aplicação.</response>
        [ResponseType(typeof(ContainerModel))]
        [HttpPost]
        [Route("{name}")]
        public IHttpActionResult PostContainer(string name, [FromBody] ContainerModel container)
        {
            // O 'name' da rota é a App Pai
            string appName = name;

            if (container == null) container = new ContainerModel();

            if (container.ResType.ToLower() != "container")
                return BadRequest("O tipo de recurso deve ser 'container'.");

            // Naming logic
            bool isAutoGenerated = string.IsNullOrEmpty(container.ResourceName);
            if (isAutoGenerated)
                container.ResourceName = "Cont_" + Guid.NewGuid().ToString().Substring(0, 8);

            container.CreationDateTime = DateTime.Now;

            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                conn.Open();

                // 1. Obter ID da App
                string sqlGetApp = "SELECT Id FROM Applications WHERE Name = @appName";
                SqlCommand cmdGetApp = new SqlCommand(sqlGetApp, conn);
                cmdGetApp.Parameters.AddWithValue("@appName", appName);
                object result = cmdGetApp.ExecuteScalar();

                if (result == null) return NotFound(); // App não existe
                int parentId = (int)result;

                // 2. Inserir Container
                while (true)
                {
                    string sqlInsert = "INSERT INTO Containers (Name, CreationDate, ParentAppId) VALUES (@name, @date, @parentId)";
                    SqlCommand cmdInsert = new SqlCommand(sqlInsert, conn);
                    cmdInsert.Parameters.AddWithValue("@name", container.ResourceName);
                    cmdInsert.Parameters.AddWithValue("@date", container.CreationDateTime);
                    cmdInsert.Parameters.AddWithValue("@parentId", parentId);

                    try
                    {
                        cmdInsert.ExecuteNonQuery();
                        break;
                    }
                    catch (SqlException ex)
                    {
                        if (ex.Number == 2627) // Nome duplicado
                        {
                            if (isAutoGenerated)
                            {
                                container.ResourceName = "Cont_" + Guid.NewGuid().ToString().Substring(0, 8);
                                continue;
                            }
                            else
                            {
                                return Content(HttpStatusCode.Conflict, "Container name already exists in this application.");
                            }
                        }
                        return InternalServerError(ex);
                    }
                }
            }
            return Content(HttpStatusCode.Created, container);
        }
    }
}