using SOMIOD.Models;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data.SqlClient;
using System.Net;
using System.Web.Http;
using System.Web.Http.Description;

namespace SOMIOD.Controllers
{
    [RoutePrefix("api/somiod")]
    public class SubscriptionController : ApiController
    {
        // Connection String
        private string connectionString = ConfigurationManager.ConnectionStrings["ConnStr"].ConnectionString;

        /// <summary>
        /// Cria uma nova subscrição num contentor.
        /// </summary>
        /// <remarks>
        /// As subscrições permitem que aplicações externas sejam notificadas quando ocorrem eventos no contentor.
        /// 
        /// **Campos Obrigatórios:**
        /// * `endpoint`: O endereço de destino (ex: `http://localhost:5000/api/endpoint` ou `mqtt://127.0.0.1:1883`).
        /// * `evt`: O tipo de evento a escutar.
        ///     * **1**: Criação (Quando uma nova Content-Instance é criada).
        ///     * **2**: Eliminação (Quando uma Content-Instance é apagada).
        /// 
        /// **Exemplo de Pedido:**
        /// 
        ///     POST /api/somiod/smart-parking/piso-01/subs
        ///     {
        ///        "res-type": "subscription",
        ///        "resource-name": "alertas-mqtt",
        ///        "endpoint": "mqtt://127.0.0.1:1883",
        ///        "evt": 1
        ///     }
        /// </remarks>
        /// <param name="appName">O nome da aplicação pai.</param>
        /// <param name="containerName">O nome do contentor pai.</param>
        /// <param name="sub">O modelo da subscrição.</param>
        /// <returns>Os dados da subscrição criada.</returns>
        /// <response code="201">Sucesso: Subscrição criada.</response>
        /// <response code="400">Erro: Endpoint em falta, Evento inválido (apenas 1 ou 2) ou Tipo incorreto.</response>
        /// <response code="404">Erro: Contentor pai não encontrado.</response>
        /// <response code="409">Conflito: Nome da subscrição já existe.</response>
        [ResponseType(typeof(SubscriptionModel))]
        [HttpPost]
        [Route("{appName}/{containerName}/subs")]
        public IHttpActionResult PostSubscription(string appName, string containerName, [FromBody] SubscriptionModel sub)
        {
            // Validações Básicas
            if (sub == null) sub = new SubscriptionModel();

            // Validação de Tipo
            if (sub.ResType.ToLower() != "subscription")
                return BadRequest("O tipo de recurso deve ser 'subscription'.");

            // Endpoint é obrigatório -> 400 Bad Request
            if (string.IsNullOrEmpty(sub.Endpoint))
                return BadRequest("O campo 'endpoint' é obrigatório.");

            // Validação de Evento (1=Criação, 2=Apagar)
            if (sub.Evt != 1 && sub.Evt != 2)
                return BadRequest("O evento (evt) deve ser 1 (Criação) ou 2 (Apagar).");

            // Verificar Container Pai
            int containerId = 0;
            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                conn.Open();
                string sqlGetContId = @"SELECT C.Id FROM Containers C 
                                        INNER JOIN Applications A ON C.ParentAppId = A.Id 
                                        WHERE A.Name = @appName AND C.Name = @contName";
                SqlCommand cmdGetId = new SqlCommand(sqlGetContId, conn);
                cmdGetId.Parameters.AddWithValue("@appName", appName);
                cmdGetId.Parameters.AddWithValue("@contName", containerName);

                object result = cmdGetId.ExecuteScalar();
                if (result == null) return NotFound(); // Container pai não existe
                containerId = (int)result;
            }

            // Naming e Datas
            bool isAutoGenerated = string.IsNullOrEmpty(sub.ResourceName);
            if (isAutoGenerated)
                sub.ResourceName = "Sub_" + Guid.NewGuid().ToString().Substring(0, 8);

            sub.CreationDateTime = DateTime.Now;

            // Inserção na BD
            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                conn.Open();
                while (true) // Retry logic para GUIDs
                {
                    string sqlInsert = @"INSERT INTO Subscriptions 
                                         (Name, CreationDate, Event, Endpoint, ParentContainerId) 
                                         VALUES (@name, @date, @evt, @endpoint, @parentId)";

                    SqlCommand cmdInsert = new SqlCommand(sqlInsert, conn);
                    cmdInsert.Parameters.AddWithValue("@name", sub.ResourceName);
                    cmdInsert.Parameters.AddWithValue("@date", sub.CreationDateTime);
                    cmdInsert.Parameters.AddWithValue("@evt", sub.Evt);
                    cmdInsert.Parameters.AddWithValue("@endpoint", sub.Endpoint);
                    cmdInsert.Parameters.AddWithValue("@parentId", containerId);

                    try
                    {
                        cmdInsert.ExecuteNonQuery();
                        break;
                    }
                    catch (SqlException ex)
                    {
                        // Recurso já existe -> 409 Conflict
                        if (ex.Number == 2627)
                        {
                            if (isAutoGenerated)
                            {
                                sub.ResourceName = "Sub_" + Guid.NewGuid().ToString().Substring(0, 8);
                                continue;
                            }
                            return Content(HttpStatusCode.Conflict, "Subscription name already exists.");
                        }
                        return InternalServerError(ex);
                    }
                }
            }

            // Sucesso -> 201 Created
            return Content(HttpStatusCode.Created, sub);
        }

        /// <summary>
        /// Obtém os detalhes de uma subscrição.
        /// </summary>
        /// <remarks>
        /// Recupera as configurações de uma subscrição específica (Endpoint e Evento de notificação).
        /// 
        /// **Comportamento Discovery:**
        /// A Subscrição é um recurso de nível inferior (folha). Se o header `somiod-discovery` for enviado, a API retorna uma lista vazia `[]`.
        /// </remarks>
        /// <param name="appName">O nome da aplicação pai.</param>
        /// <param name="containerName">O nome do contentor pai.</param>
        /// <param name="subName">O nome da subscrição a recuperar.</param>
        /// <returns>O objeto SubscriptionModel com os dados.</returns>
        /// <response code="200">Sucesso: Retorna o objeto (ou lista vazia em discovery).</response>
        /// <response code="404">Erro: Recurso não encontrado (App, Contentor ou Subscrição inexistentes).</response>
        [ResponseType(typeof(SubscriptionModel))]
        [HttpGet]
        [Route("{appName}/{containerName}/subs/{subName}")]
        public IHttpActionResult GetSubscription(string appName, string containerName, string subName)
        {
            // Validar Existência (Hierarquia Completa)
            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                conn.Open();
                string sqlCheck = @"SELECT S.Id FROM Subscriptions S
                                    INNER JOIN Containers C ON S.ParentContainerId = C.Id
                                    INNER JOIN Applications A ON C.ParentAppId = A.Id
                                    WHERE A.Name = @appName AND C.Name = @contName AND S.Name = @subName";
                SqlCommand cmdCheck = new SqlCommand(sqlCheck, conn);
                cmdCheck.Parameters.AddWithValue("@appName", appName);
                cmdCheck.Parameters.AddWithValue("@contName", containerName);
                cmdCheck.Parameters.AddWithValue("@subName", subName);

                if (cmdCheck.ExecuteScalar() == null) return NotFound();
            }

            // Lógica de Discovery (Leaf Node)
            // Discovery num item folha retorna lista vazia (200 OK)
            if (Request.Headers.Contains("somiod-discovery"))
            {
                return Ok(new List<string>());
            }

            // Leitura Normal
            SubscriptionModel sub = null;
            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                string sql = @"SELECT S.Id, S.Name, S.CreationDate, S.Event, S.Endpoint, S.ParentContainerId
                               FROM Subscriptions S
                               INNER JOIN Containers C ON S.ParentContainerId = C.Id
                               INNER JOIN Applications A ON C.ParentAppId = A.Id
                               WHERE A.Name = @appName AND C.Name = @contName AND S.Name = @subName";

                SqlCommand cmd = new SqlCommand(sql, conn);
                cmd.Parameters.AddWithValue("@appName", appName);
                cmd.Parameters.AddWithValue("@contName", containerName);
                cmd.Parameters.AddWithValue("@subName", subName);
                conn.Open();

                SqlDataReader reader = cmd.ExecuteReader();
                if (reader.Read())
                {
                    sub = new SubscriptionModel
                    {
                        Id = (int)reader["Id"],
                        ResourceName = (string)reader["Name"],
                        CreationDateTime = (DateTime)reader["CreationDate"],
                        Evt = Convert.ToInt32(reader["Event"]),
                        Endpoint = (string)reader["Endpoint"],
                        ParentId = (int)reader["ParentContainerId"],
                        ResType = "subscription"
                    };
                }
            }
            return Ok(sub);
        }

        /// <summary>
        /// Remove uma subscrição existente.
        /// </summary>
        /// <remarks>
        /// Apaga a subscrição da base de dados.
        /// A partir deste momento, o endpoint configurado deixará de receber notificações deste contentor.
        /// </remarks>
        /// <param name="appName">O nome da aplicação pai.</param>
        /// <param name="containerName">O nome do contentor pai.</param>
        /// <param name="subName">O nome da subscrição a remover.</param>
        /// <returns>Sem conteúdo.</returns>
        /// <response code="200">Sucesso: Subscrição apagada.</response>
        /// <response code="404">Erro: Recurso não encontrado.</response>
        [ResponseType(typeof(void))]
        [HttpDelete]
        [Route("{appName}/{containerName}/subs/{subName}")]
        public IHttpActionResult DeleteSubscription(string appName, string containerName, string subName)
        {
            using (SqlConnection conn = new SqlConnection(connectionString))
            {
                // Delete com Join para garantir hierarquia
                string sql = @"DELETE S FROM Subscriptions S
                               INNER JOIN Containers C ON S.ParentContainerId = C.Id
                               INNER JOIN Applications A ON C.ParentAppId = A.Id
                               WHERE A.Name = @appName AND C.Name = @contName AND S.Name = @subName";

                SqlCommand cmd = new SqlCommand(sql, conn);
                cmd.Parameters.AddWithValue("@appName", appName);
                cmd.Parameters.AddWithValue("@contName", containerName);
                cmd.Parameters.AddWithValue("@subName", subName);
                conn.Open();

                if (cmd.ExecuteNonQuery() == 0) return NotFound();
            }
            return Ok();
        }
    }
}